// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 14.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ranta.Lucy.Core.Database.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class SqlServerProjectTemplate : SqlServerProjectTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"<?xml version=""1.0"" encoding=""utf-8""?>
<Project DefaultTargets=""Build"" xmlns=""http://schemas.microsoft.com/developer/msbuild/2003"" ToolsVersion=""4.0"">
  <Import Project=""$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props"" Condition=""Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')"" />
  <PropertyGroup>
    <Configuration Condition="" '$(Configuration)' == '' "">Debug</Configuration>
    <Platform Condition="" '$(Platform)' == '' "">AnyCPU</Platform>
    <Name>");
            
            #line 12 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Project.FullName));
            
            #line default
            #line hidden
            this.Write("</Name>\r\n    <SchemaVersion>2.0</SchemaVersion>\r\n    <ProjectVersion>4.1</Project" +
                    "Version>\r\n    <ProjectGuid>{09d1fc8b-e0bc-428a-b128-7136ccc622dc}</ProjectGuid>\r" +
                    "\n    <DSP>Microsoft.Data.Tools.Schema.Sql.Sql110DatabaseSchemaProvider</DSP>\r\n  " +
                    "  <OutputType>Database</OutputType>\r\n    <RootPath>\r\n    </RootPath>\r\n    <RootN" +
                    "amespace>Tmp.Lucy.Database</RootNamespace>\r\n    <AssemblyName>Tmp.Lucy.Database<" +
                    "/AssemblyName>\r\n    <ModelCollation>1033, CI</ModelCollation>\r\n    <DefaultFileS" +
                    "tructure>BySchemaAndSchemaType</DefaultFileStructure>\r\n    <DeployToDatabase>Tru" +
                    "e</DeployToDatabase>\r\n    <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>\r" +
                    "\n    <TargetLanguage>CS</TargetLanguage>\r\n    <AppDesignerFolder>Properties</App" +
                    "DesignerFolder>\r\n    <SqlServerVerification>False</SqlServerVerification>\r\n    <" +
                    "IncludeCompositeObjects>True</IncludeCompositeObjects>\r\n    <TargetDatabaseSet>T" +
                    "rue</TargetDatabaseSet>\r\n  </PropertyGroup>\r\n  <PropertyGroup Condition=\" \'$(Con" +
                    "figuration)|$(Platform)\' == \'Release|AnyCPU\' \">\r\n    <OutputPath>bin\\Release\\</O" +
                    "utputPath>\r\n    <BuildScriptName>$(MSBuildProjectName).sql</BuildScriptName>\r\n  " +
                    "  <TreatWarningsAsErrors>False</TreatWarningsAsErrors>\r\n    <DebugType>pdbonly</" +
                    "DebugType>\r\n    <Optimize>true</Optimize>\r\n    <DefineDebug>false</DefineDebug>\r" +
                    "\n    <DefineTrace>true</DefineTrace>\r\n    <ErrorReport>prompt</ErrorReport>\r\n   " +
                    " <WarningLevel>4</WarningLevel>\r\n  </PropertyGroup>\r\n  <PropertyGroup Condition=" +
                    "\" \'$(Configuration)|$(Platform)\' == \'Debug|AnyCPU\' \">\r\n    <OutputPath>bin\\Debug" +
                    "\\</OutputPath>\r\n    <BuildScriptName>$(MSBuildProjectName).sql</BuildScriptName>" +
                    "\r\n    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>\r\n    <DebugSymbols>tr" +
                    "ue</DebugSymbols>\r\n    <DebugType>full</DebugType>\r\n    <Optimize>false</Optimiz" +
                    "e>\r\n    <DefineDebug>true</DefineDebug>\r\n    <DefineTrace>true</DefineTrace>\r\n  " +
                    "  <ErrorReport>prompt</ErrorReport>\r\n    <WarningLevel>4</WarningLevel>\r\n  </Pro" +
                    "pertyGroup>\r\n  <!-- VS10 without SP1 will not have VisualStudioVersion set, so d" +
                    "o that here -->\r\n  <PropertyGroup>\r\n    <VisualStudioVersion Condition=\"\'$(Visua" +
                    "lStudioVersion)\' == \'\'\">10.0</VisualStudioVersion>\r\n    <!-- Default to the v10." +
                    "0 targets path if the targets file for the current VS version is not found -->\r\n" +
                    "    <SSDTExists Condition=\"Exists(\'$(MSBuildExtensionsPath)\\Microsoft\\VisualStud" +
                    "io\\v$(VisualStudioVersion)\\SSDT\\Microsoft.Data.Tools.Schema.SqlTasks.targets\')\">" +
                    "True</SSDTExists>\r\n    <VisualStudioVersion Condition=\"\'$(SSDTExists)\' == \'\'\">10" +
                    ".0</VisualStudioVersion>\r\n  </PropertyGroup>\r\n  <Import Project=\"$(MSBuildExtens" +
                    "ionsPath)\\Microsoft\\VisualStudio\\v$(VisualStudioVersion)\\SSDT\\Microsoft.Data.Too" +
                    "ls.Schema.SqlTasks.targets\" />\r\n  <ItemGroup>\r\n    <Folder Include=\"Properties\" " +
                    "/>\r\n");
            
            #line 65 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"

    foreach(var schema in this.Project.Schemas)
    {

            
            #line default
            #line hidden
            this.Write("    <Folder Include=\"");
            
            #line 69 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema.Key));
            
            #line default
            #line hidden
            this.Write("\" />\r\n    <Folder Include=\"");
            
            #line 70 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema.Key));
            
            #line default
            #line hidden
            this.Write("\\Table\" />\r\n    <Folder Include=\"");
            
            #line 71 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema.Key));
            
            #line default
            #line hidden
            this.Write("\\Tvp\" />\r\n    <Folder Include=\"");
            
            #line 72 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema.Key));
            
            #line default
            #line hidden
            this.Write("\\StoredProcedure\" />\r\n");
            
            #line 73 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("  </ItemGroup>\r\n  <ItemGroup>\r\n");
            
            #line 78 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"

    foreach(var schema in this.Project.Schemas)
    {

            
            #line default
            #line hidden
            this.Write("    <Build Include=\"");
            
            #line 82 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema.Key));
            
            #line default
            #line hidden
            this.Write("\\");
            
            #line 82 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema.Key));
            
            #line default
            #line hidden
            this.Write(".sql\" />\r\n");
            
            #line 83 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"

        foreach(var table in schema.Value.Tables)
        {

            
            #line default
            #line hidden
            this.Write("    <Build Include=\"");
            
            #line 87 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema.Key));
            
            #line default
            #line hidden
            this.Write("\\Table\\");
            
            #line 87 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name));
            
            #line default
            #line hidden
            this.Write(".sql\" />\r\n    <Build Include=\"");
            
            #line 88 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema.Key));
            
            #line default
            #line hidden
            this.Write("\\Tvp\\Tvp_");
            
            #line 88 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.Name));
            
            #line default
            #line hidden
            this.Write(".sql\" />\r\n    <Build Include=\"");
            
            #line 89 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema.Key));
            
            #line default
            #line hidden
            this.Write("\\StoredProcedure\\");
            
            #line 89 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.UnderlineFullName));
            
            #line default
            #line hidden
            this.Write("\\SP_Insert_");
            
            #line 89 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.UnderlineFullName));
            
            #line default
            #line hidden
            this.Write(".sql\" />\r\n    <Build Include=\"");
            
            #line 90 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema.Key));
            
            #line default
            #line hidden
            this.Write("\\StoredProcedure\\");
            
            #line 90 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.UnderlineFullName));
            
            #line default
            #line hidden
            this.Write("\\SP_InsertTvp_");
            
            #line 90 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.UnderlineFullName));
            
            #line default
            #line hidden
            this.Write(".sql\" />\r\n    <Build Include=\"");
            
            #line 91 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema.Key));
            
            #line default
            #line hidden
            this.Write("\\StoredProcedure\\");
            
            #line 91 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.UnderlineFullName));
            
            #line default
            #line hidden
            this.Write("\\SP_Update_");
            
            #line 91 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.UnderlineFullName));
            
            #line default
            #line hidden
            this.Write(".sql\" />\r\n    <Build Include=\"");
            
            #line 92 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema.Key));
            
            #line default
            #line hidden
            this.Write("\\StoredProcedure\\");
            
            #line 92 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.UnderlineFullName));
            
            #line default
            #line hidden
            this.Write("\\SP_UpdateTvp_");
            
            #line 92 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.UnderlineFullName));
            
            #line default
            #line hidden
            this.Write(".sql\" />\r\n    <Build Include=\"");
            
            #line 93 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema.Key));
            
            #line default
            #line hidden
            this.Write("\\StoredProcedure\\");
            
            #line 93 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.UnderlineFullName));
            
            #line default
            #line hidden
            this.Write("\\SP_Delete_");
            
            #line 93 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.UnderlineFullName));
            
            #line default
            #line hidden
            this.Write(".sql\" />\r\n    <Build Include=\"");
            
            #line 94 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema.Key));
            
            #line default
            #line hidden
            this.Write("\\StoredProcedure\\");
            
            #line 94 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.UnderlineFullName));
            
            #line default
            #line hidden
            this.Write("\\SP_DeleteTvp_");
            
            #line 94 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.UnderlineFullName));
            
            #line default
            #line hidden
            this.Write(".sql\" />\r\n    <Build Include=\"");
            
            #line 95 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema.Key));
            
            #line default
            #line hidden
            this.Write("\\StoredProcedure\\");
            
            #line 95 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.UnderlineFullName));
            
            #line default
            #line hidden
            this.Write("\\SP_Get_");
            
            #line 95 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.UnderlineFullName));
            
            #line default
            #line hidden
            this.Write(".sql\" />\r\n    <Build Include=\"");
            
            #line 96 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema.Key));
            
            #line default
            #line hidden
            this.Write("\\StoredProcedure\\");
            
            #line 96 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.UnderlineFullName));
            
            #line default
            #line hidden
            this.Write("\\SP_Query_");
            
            #line 96 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.UnderlineFullName));
            
            #line default
            #line hidden
            this.Write(".sql\" />\r\n");
            
            #line 97 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"

        }

            
            #line default
            #line hidden
            
            #line 100 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Database\Template\SqlServerProjectTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("  </ItemGroup>\r\n</Project>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class SqlServerProjectTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
