// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 14.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ranta.Lucy.Core.Template.Business
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Template\Business\CSharp_Business_Project_Template.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class CSharp_Business_Project_Template : CSharp_Business_Project_TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"<Project ToolsVersion=""4.0"" DefaultTargets=""Build"" xmlns=""http://schemas.microsoft.com/developer/msbuild/2003"">
  <Import Project=""$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props"" Condition=""Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')"" />
  <PropertyGroup>
    <Configuration Condition="" '$(Configuration)' == '' "">Debug</Configuration>
    <Platform Condition="" '$(Platform)' == '' "">AnyCPU</Platform>
    <ProjectGuid>{");
            
            #line 11 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Template\Business\CSharp_Business_Project_Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Project.ProjectGuid.ToString()));
            
            #line default
            #line hidden
            this.Write("}</ProjectGuid>\r\n    <OutputType>Library</OutputType>\r\n    <AppDesignerFolder>Pro" +
                    "perties</AppDesignerFolder>\r\n    <RootNamespace>");
            
            #line 14 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Template\Business\CSharp_Business_Project_Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Project.FullName));
            
            #line default
            #line hidden
            this.Write("</RootNamespace>\r\n    <AssemblyName>");
            
            #line 15 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Template\Business\CSharp_Business_Project_Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Project.FullName));
            
            #line default
            #line hidden
            this.Write("</AssemblyName>\r\n    <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>\r\n    <" +
                    "FileAlignment>512</FileAlignment>\r\n    <SccProjectName></SccProjectName>\r\n    <S" +
                    "ccLocalPath></SccLocalPath>\r\n    <SccAuxPath></SccAuxPath>\r\n    <SccProvider></S" +
                    "ccProvider>\r\n  </PropertyGroup>\r\n  <PropertyGroup Condition=\" \'$(Configuration)|" +
                    "$(Platform)\' == \'Debug|AnyCPU\' \">\r\n    <DebugSymbols>true</DebugSymbols>\r\n    <D" +
                    "ebugType>full</DebugType>\r\n    <Optimize>false</Optimize>\r\n    <OutputPath>bin\\D" +
                    "ebug\\</OutputPath>\r\n    <DefineConstants>DEBUG;TRACE</DefineConstants>\r\n    <Err" +
                    "orReport>prompt</ErrorReport>\r\n    <WarningLevel>4</WarningLevel>\r\n  </PropertyG" +
                    "roup>\r\n  <PropertyGroup Condition=\" \'$(Configuration)|$(Platform)\' == \'Release|A" +
                    "nyCPU\' \">\r\n    <DebugType>pdbonly</DebugType>\r\n    <Optimize>true</Optimize>\r\n  " +
                    "  <OutputPath>bin\\Release\\</OutputPath>\r\n    <DefineConstants>TRACE</DefineConst" +
                    "ants>\r\n    <ErrorReport>prompt</ErrorReport>\r\n    <WarningLevel>4</WarningLevel>" +
                    "\r\n  </PropertyGroup>\r\n  <ItemGroup>\r\n    <Reference Include=\"log4net\">\r\n      <H" +
                    "intPath>..\\packages\\log4net.2.0.3\\lib\\net40-full\\log4net.dll</HintPath>\r\n    </R" +
                    "eference>\r\n    <Reference Include=\"System\" />\r\n    <Reference Include=\"System.Co" +
                    "re\" />\r\n    <Reference Include=\"System.Xml.Linq\" />\r\n    <Reference Include=\"Sys" +
                    "tem.Data.DataSetExtensions\" />\r\n    <Reference Include=\"Microsoft.CSharp\" />\r\n  " +
                    "  <Reference Include=\"System.Data\" />\r\n    <Reference Include=\"System.Xml\" />\r\n " +
                    " </ItemGroup>\r\n  <ItemGroup>\r\n    <Compile Include=\"Properties\\AssemblyInfo.cs\" " +
                    "/>\r\n");
            
            #line 54 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Template\Business\CSharp_Business_Project_Template.tt"

    foreach (var schema in this.Project.Schemas)
    {
        foreach (var table in schema.Value.Tables)
        {

            
            #line default
            #line hidden
            this.Write("    <Compile Include=\"");
            
            #line 60 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Template\Business\CSharp_Business_Project_Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Format(@"Models\{0}Model.cs", table.CsFullName)));
            
            #line default
            #line hidden
            this.Write("\" />\r\n    <Compile Include=\"");
            
            #line 61 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Template\Business\CSharp_Business_Project_Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Format(@"Convertors\{0}Convertor.cs", table.CsFullName)));
            
            #line default
            #line hidden
            this.Write("\" />\r\n    <Compile Include=\"");
            
            #line 62 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Template\Business\CSharp_Business_Project_Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Format(@"Managers\{0}Manager.cs", table.CsFullName)));
            
            #line default
            #line hidden
            this.Write("\" />\r\n    <Compile Include=\"");
            
            #line 63 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Template\Business\CSharp_Business_Project_Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Format(@"Managers\Partial\{0}Manager.cs", table.CsFullName)));
            
            #line default
            #line hidden
            this.Write("\" />\r\n");
            
            #line 64 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Template\Business\CSharp_Business_Project_Template.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("  </ItemGroup>\r\n  <ItemGroup>\r\n");
            
            #line 70 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Template\Business\CSharp_Business_Project_Template.tt"

    if(this.Project.ReferencedProjects != null && this.Project.ReferencedProjects.Count > 0)
    {
        foreach(var project in this.Project.ReferencedProjects)
        {

            
            #line default
            #line hidden
            this.Write("    <ProjectReference Include=\"..\\");
            
            #line 76 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Template\Business\CSharp_Business_Project_Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.FullName));
            
            #line default
            #line hidden
            this.Write("\\");
            
            #line 76 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Template\Business\CSharp_Business_Project_Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.FullName));
            
            #line default
            #line hidden
            this.Write(".csproj\">\r\n      <Project>{");
            
            #line 77 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Template\Business\CSharp_Business_Project_Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.ProjectGuid.ToString()));
            
            #line default
            #line hidden
            this.Write("}</Project>\r\n      <Name>");
            
            #line 78 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Template\Business\CSharp_Business_Project_Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.FullName));
            
            #line default
            #line hidden
            this.Write("</Name>\r\n    </ProjectReference>\r\n");
            
            #line 80 "D:\GitblitWorkspace\ranta-app\Lucy\Ranta.Lucy.Core\Template\Business\CSharp_Business_Project_Template.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("  </ItemGroup>\r\n  <Import Project=\"$(MSBuildToolsPath)\\Microsoft.CSharp.targets\" " +
                    "/>\r\n</Project>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class CSharp_Business_Project_TemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
